name: CRD Java Model Generate
on:
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run CRD Model Generation
        run: |
          docker run \
            --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v "$(pwd)":"$(pwd)" \
            --network host \
            ghcr.io/kubernetes-client/java/crd-model-gen:v1.0.6 \
            /generate.sh \
            -u https://raw.githubusercontent.com/iendi/java/master/examples/examples-release-17/test.yaml  \
            -n io.k8s.networking.gateway \
            -p io.k8s.networking.gateway \
            -o "$(pwd)"\
      - name: List Generated Files
        run: |
          ls -lh
      - uses: actions/upload-artifact@v4
        with:
          name: generated-java-crd-model
          path: .
